// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/HUD/MortarInfo/RadiationInfo.layout
class RAD_RadiationInfoWidgets
{
	protected static const ResourceName LAYOUT = "{A4E55F8F17688660}UI/layouts/HUD/MortarInfo/RadiationInfo.layout";

	ImageWidget m_wImage;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wImage = ImageWidget.Cast(root.FindWidget("Overlay.m_Image"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
